muffler=data.frame(discount=c(2.0,4.0,6.0,8.0,10.0),profit=c(0,0,0,1,1))
plot(muffler,pch=20,cex=2,xlim=c(0,12))
haberman=read.csv("https://archive.ics.uci.edu/ml/machine-learning-databases/haberman/haberman.data",header=FALSE)
names(haberman)=c('age','op_year','no_nodes','survival')
str(haberman)
haberman$survival=factor(haberman$survival)
h=glm(survival~age+op_year+no_nodes, data=haberman,family=binomial)
coef(h)
deviance(h)